# Generated by Django 4.2.9 on 2024-01-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="link",
            field=models.CharField(default="www.spug.com", max_length=255),
        ),
    ]
