# Generated by Django 4.2.9 on 2024-01-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0002_task_link"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="link",),
        migrations.RemoveField(model_name="task", name="period",),
        migrations.AddField(
            model_name="task",
            name="period_months",
            field=models.IntegerField(default=0, verbose_name="Period (Months)"),
        ),
        migrations.AddField(
            model_name="task",
            name="period_years",
            field=models.IntegerField(default=0, verbose_name="Period (Years)"),
        ),
    ]
