# Generated by Django 4.2.9 on 2024-01-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0003_remove_task_link_remove_task_period_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task", name="start_time", field=models.DateField(),
        ),
    ]
