# Generated by Django 4.2.9 on 2024-01-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0004_alter_task_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="Ding",
            field=models.CharField(default="ding_access_token", max_length=255),
        ),
        migrations.AddField(
            model_name="task",
            name="link",
            field=models.CharField(default="spug.com", max_length=255),
        ),
    ]
