# Generated by Django 4.2.9 on 2024-01-11 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0005_task_ding_task_link"),
    ]

    operations = [
        migrations.RenameField(model_name="task", old_name="Ding", new_name="ding",),
    ]
