# Generated by Django 4.2.9 on 2024-01-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0007_task_period_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="ding",
            field=models.CharField(
                default="https://oapi.dingtalk.com/robot/send?access_token=858cbe8a1d55ed763ce6e794bb3ff8dcbdc8dc882bd92861ec848e51e1163201",
                max_length=255,
            ),
        ),
    ]
