# Generated by Django 4.2.9 on 2024-01-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0008_alter_task_ding"),
    ]

    operations = [
        migrations.AddField(
            model_name="task", name="created", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="notified",
            field=models.BooleanField(default=False),
        ),
    ]
