# Generated by Django 4.2.9 on 2024-01-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0010_alter_task_created_alter_task_notified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task", name="created", field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="notified",
            field=models.BooleanField(default=False),
        ),
    ]
