# Generated by Django 4.2.9 on 2024-01-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0011_alter_task_created_alter_task_notified"),
    ]

    operations = [
        migrations.AddField(
            model_name="task", name="extended", field=models.IntegerField(default=1),
        ),
    ]
