# Generated by Django 4.2.9 on 2024-01-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0013_alter_task_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="note_days",
            field=models.IntegerField(
                default=2, verbose_name="Days before expire to notice"
            ),
        ),
    ]
