# Generated by Django 4.2.9 on 2024-01-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0014_task_note_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="notified_times",
            field=models.IntegerField(
                default=1, verbose_name="How many times to notify"
            ),
        ),
        migrations.AlterField(
            model_name="task", name="notified", field=models.IntegerField(default=1),
        ),
    ]
