# Generated by Django 4.2.9 on 2024-01-16 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0015_task_notified_times_alter_task_notified"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="extended",),
        migrations.AddField(
            model_name="task",
            name="end_date",
            field=models.DateField(default=datetime.date(2024, 1, 15)),
        ),
    ]
